### ISSUE TITLE
Is attention normalization method right?

### ISSUE THREAD

**Issue by candlewill** [r9y9/deepvoice3_pytorch#23]
@r9y9 To my understanding, `x = x * (s * math.sqrt(1.0 / s))` == `x = x * (math.sqrt(s))`. Is this right?

If it is right, why we need to multiply `x` with `math.sqrt(s)` instead of divided by `math.sqrt(s)` ?

https://github.com/r9y9/deepvoice3_pytorch/blob/ec58290770abebcc8039b0064d0590f69ee4f289/deepvoice3_pytorch/deepvoice3.py#L172

**Comment by r9y9** [comment]
I think you are right. To note, this is because the code was adapted from fairseq https://github.com/facebookresearch/fairseq-py/blob/9430544a3b95dbb2e3b86c303776e37f18188ad3/fairseq/models/fconv.py#L139

They use the notation `m * sqrt(1/m)` in their paper (see sec. 3.4 of https://arxiv.org/pdf/1705.03122.pdf) and I guess this is why the code as is.
