### ISSUE TITLE
Changing fft_size, hop_size in hparams.py?

### ISSUE THREAD

**Issue by t3t3t3** [r9y9/deepvoice3_pytorch#27]
Hi there,

I changed hparams.py to

   fft_size=2052, # default 1024
   hop_size=114, # fedault 256

And I get un-audible result!

What should I do, if I want to increase the fft_size & reduce hop_size? What did I do wrong?

Thanks a lot for any help!

**Comment by r9y9** [comment]
I use lws for phase reconstruction. It's great, however, it seems not well tested (https://github.com/Jonathan-LeRoux/lws/issues/1). I'd recommend you to make sure you can get good reconstruction with your hyper parameters first.

As far as I remember correctly, fft_size=2048 and hop_size=256 worked reasonably. I reduced it to save computational costs.

**Comment by t3t3t3** [comment]
I test the reconstruction with fft_size=2052 and hop_size=114 with:

import audio
p='LJSpeech-1.0/wavs/LJ035-0167.wav'
w=audio.load_wav(p)
s2=audio.spectrogram(w)
w2=audio.inv_spectrogram(s2)
audio.save_wav(w,'t1.wav')
audio.save_wav(w2,'t2.wav')

And everything is fine. The un-audible result is outcome of training (found at checkpoints/eval ). I will try again with fft_size=2048 and hop_size=256 to see if it works better.

**Comment by t3t3t3** [comment]
fft_size=2048 and hop_size=256 works. I have not looked into why some values works and other not.

**Comment by imdatsolak** [comment]
@t3t3t3 : you should check the FIRST checkpoints/eval file after starting training. That one should be kind-a ok. The rest is inaudible also in my case. I have fft_size=2048, hop_size=256.
The same happens when I do "synthesis.py". The first text is synthesized ok, the other texts are inaudible (if I use a text-file with more than one line).

In my case, if I start "synthesis.py" for every text from scratch, the output is ok (depending on the epoch). If I start it with multiple lines of text, the first is ok, the others are inaudible... I'm still exploring what the problem is...
