### ISSUE TITLE
jsut data

### ISSUE THREAD

**Issue by Kyubyong** [r9y9/deepvoice3_pytorch#61]
Hi,

When you train on the JSUT corpus, did you use the original Japanese script? What I'm curious is Chinese characters are not phonetic, so I doubt if the network can learn with them. I thought they need to be converted into phonetic transcription (romaji).

**Comment by r9y9** [comment]
Sorry for late. I used mixed inputs of original script and its pronunciation (in my case, katakana representation of raw script instead of romaji). Ultimately, I would expect a model can learn grapheme-to-phoneme (g2p) model with original inputs, but practically I was wondering if it works well. The reason I didn't use phonetic transcription directly is that I wanted to explore how an end-to-end model fits Japanese language with original scripts. As you have may guessed, from my limited experience though, I realized that training an end-to-end TTS model that can do g2p for Japanese is extremely difficult with small amount of data (~10 hours).

**Comment by Kyubyong** [comment]
Thanks so much!
